app = 'yral-ml-feed-server'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
[build.args]
NONROOT_USER = "pythonuser" # Access this value in the Dockerfile using `ARG NONROOT_USER`

[env]
PORT = '8080'

[processes]
rust_proc = "./ml-feed-rust"
python_proc = "/bin/bash -c ./entrypoint.sh $PYTHON_USER"

[[services]]
internal_port = 50051
protocol = "tcp"
processes = ["rust_proc"]

[[services.ports]]
handlers = ["tls"]
tls_options = { "alpn" = ["h2"], "versions" = ["TLSv1.2", "TLSv1.3"] }
port = 443

[services.concurrency]
hard_limit = 1000
soft_limit = 500

[[vm]]
memory = '8gb'
cpu_kind = 'shared'
cpus = 8

[mounts]
source = "data"
destination = "/home/pythonuser"
initial_size = "50gb"
