app = 'yral-ml-feed-server'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
PORT = '8080'

[processes]
# The command below is used to launch a Rails server; be sure to
# replace with the command you're using to launch your server.
web = "./ml_feed_rust"
# cron = "supercronic /app/crontab"

[[services]]
internal_port = 50051
protocol = "tcp"
processes = ["web"]

[[services.ports]]
handlers = ["tls"]
tls_options = { "alpn" = ["h2"], "versions" = ["TLSv1.2", "TLSv1.3"] }
port = 443

[services.concurrency]
hard_limit = 1000
soft_limit = 500

[[vm]]
memory = '8gb'
cpu_kind = 'shared'
cpus = 8
