name: Deploy to Fly on push to main
on:
  workflow_dispatch:
  push:
    branches:
      - stage

jobs:
  build_check_staging:
    uses: ./.github/workflows/build-check-staging.yml
    with:
      publish-artifact: true

  deploy:
    name: Deploy
    needs: build_check_staging

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-musl
      - run: chmod 0777 target/x86_64-unknown-linux-musl/release/ml-feed-rust
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set cloudflare token
        run: |
          flyctl secrets set --stage --app "yral-ml-feed-server-staging" "UPSTASH_URL=$UPSTASH_URL"
          flyctl secrets set --stage --app "yral-ml-feed-server-staging" "UPSTASH_TOKEN=$UPSTASH_TOKEN"
          flyctl secrets set --stage --app "yral-ml-feed-server-staging" PROJECT="hot-or-not-feed-intelligence"
          flyctl secrets set --stage --app "yral-ml-feed-server-staging" "SERVICE_CRED=$SERVICE_CRED"
          flyctl secrets set --stage --app "yral-ml-feed-server-staging" GS_VIDEO_BUCKET="yral-videos"
          flyctl secrets set --stage --app "yral-ml-feed-server-staging" "GRPC_OFF_CHAIN_JWT_TOKEN=$GRPC_OFF_CHAIN_JWT_TOKEN"
        env:
          FLY_API_TOKEN: ${{ secrets.YRAL_GPU_COMPUTE_TASKS_GITHUB_ACTION_FLY_IO_DEPLOYMENT_TOKEN }}
          UPSTASH_URL: ${{ secrets.UPSTASH_URL }}
          UPSTASH_TOKEN: ${{ secrets.UPSTASH_TOKEN }}
          SERVICE_CRED: ${{ secrets.SERVICE_CRED }}
          GRPC_OFF_CHAIN_JWT_TOKEN: ${{ secrets.ENCODED_JWT_TOKEN_FOR_CALLING_ML_FEED_SERVER_FROM_OFFCHAIN_AGENT_SERVER }}
      - name: Deploy a docker container to fly.io
        run: flyctl deploy --remote-only --yes -c fly-staging.toml
        env:
          FLY_API_TOKEN: ${{ secrets.YRAL_GPU_COMPUTE_TASKS_GITHUB_ACTION_FLY_IO_DEPLOYMENT_TOKEN }}
